project:
  type: website
  output-dir: docs
  resources:
    - files/cv.pdf
    - .nojekyll

website:
  title: "Alessio Gaggero"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
    search: false

format:
  html:
    page-layout: full
    fontsize: 100%
    linestretch: 1.5
    theme: darkly
    css: styles.css
    toc: false
